learning_rate: 0.001
batch_size: 2048
context: 5
num_samples: 1000
img_size: 64
patch_size: 8

query_dim: 256
mha_heads: 2
num_tr_layers: 4
time_embedding: 256
attention_emb_dim: 256

backbone: 'resnet18'
dataset_type: mnist
dataset_config : "/ssd_scratch/cvit/keshav/DL-Project/"
ckpt_dir: '/ssd_scratch/cvit/keshav/mlns_a1_ckpts'